version: "3.9"

services:
  notifications:
    image: registry.services.phlx.ru/notifications:latest
    volumes:
    - ./configs:/data/conf
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        tag: "{{.ImageName}}|{{.Name}}|{{.ID}}"
    deploy:
      labels:
        traefik.enable: "true"
        traefik.backend: notifications
        traefik.http.routers.notifications.entrypoints: https
        traefik.http.routers.notifications.tls: "true"
        traefik.http.routers.notifications.tls.certresolver: letsencrypt
        traefik.http.routers.notifications.rule: Host(`notifications.services.${DOMAIN}`)
        traefik.http.services.notifications.loadbalancer.server.port: 8000
      placement:
        constraints:
          - "node.labels.cluster==swarm"
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
