{
 "title": "notifications",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "service",
    "query": "*, notifications_server, notifications_worker"
   },
   { "name": "protocol", "query": "http, grpc" }
  ]
 },
 "panels": [
  {
   "title": "biz",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "biz success counts [$service]",
     "type": "timeseries",
     "description": "Business logic counters",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode(stats_counts.$service.biz.*.*.success, 1, 4)"
      }
     ]
    },
    {
     "title": "biz timings (mean) [$service]",
     "type": "timeseries",
     "description": "Business logic timings",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode(stats.timers.$service.biz.*.*.timings.mean, 2, 5)"
      }
     ]
    },
    {
     "title": "biz failure counts [$service]",
     "type": "timeseries",
     "description": "Business logic counters",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode(stats_counts.$service.biz.*.*.failure, 1, 4)"
      }
     ]
    }
   ]
  },
  {
   "title": "http & grpc",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "counts [$protocol] [$service]",
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode(stats.timers.$service.$protocol.*.*.count, 2, 5)"
      }
     ]
    },
    {
     "title": "timings (mean) [$protocol]",
     "type": "timeseries",
     "description": "Business logic timings",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode(stats.timers.$service.$protocol.*.*.mean, 2, 5)"
      }
     ]
    }
   ]
  },
  { "title": "data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "counts [$service]",
   "type": "timeseries",
   "description": "Database counts",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(stats.timers.$service.data.*.*.timings.count, 2, 4, 5)"
    }
   ]
  },
  {
   "title": "timings (mean) [$service]",
   "type": "timeseries",
   "description": "Database timings",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "aliasByNode(stats.timers.$service.data.*.*.timings.mean, 2, 4, 5)"
    }
   ]
  },
  {
   "title": "senders",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "senders success counts [$service]",
     "type": "timeseries",
     "description": "Senders counters",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode(stats_counts.$service.senders.*.*.success, 1, 3, 4)"
      }
     ]
    },
    {
     "title": "senders timings (mean) [$service]",
     "type": "timeseries",
     "description": "Senders timings",
     "gridPos": { "h": 14, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "target": "aliasByNode(stats.timers.$service.senders.*.*.timings.mean, 2, 3, 4)"
      }
     ]
    },
    {
     "title": "senders failure counts [$service]",
     "type": "timeseries",
     "description": "Senders counters",
     "gridPos": { "h": 14, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "target": "aliasByNode(stats_counts.$service.senders.*.*.failure, 1, 3, 4)"
      }
     ]
    }
   ]
  },
  { "title": "postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "postgres connections [$service]",
   "type": "timeseries",
   "description": "PostgreSQL connections ",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.$service.postgres.*.connections.*, 2, 4, 6)"
    }
   ]
  },
  { "title": "golang", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "memory allocs [$service]",
   "type": "timeseries",
   "description": "Golang memory allocations",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "target": "aliasByNode(stats.gauges.$service.go.*.mem_*, 2, 4, 5)"
    }
   ]
  },
  {
   "title": "goroutines and threads [$service]",
   "type": "timeseries",
   "description": "Golang goroutines and threads",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "stats.gauges.$service.go.*.goroutines"
    },
    {
     "target": "stats.gauges.$service.go.*.threads"
    }
   ]
  },
  {
   "title": "timings (mean) [$service]",
   "type": "timeseries",
   "description": "Database timings",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "target": "aliasByNode(stats.timers.$service.go.*.gc_pause_microseconds.mean, 2, 4, 5)"
    }
   ]
  }
 ]
}