// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"notifications/internal/biz"
	"notifications/internal/conf"
	"notifications/internal/data"
	"notifications/internal/pkg/metrics"
	"notifications/internal/senders"
	"notifications/internal/worker"
)

// Injectors from wire.go:

// wireData init database
func wireData(confData *conf.Data, logger log.Logger) (data.Database, func(), error) {
	database, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	return database, func() {
		cleanup()
	}, nil
}

func wireWorker(database data.Database, sendersSenders *senders.Senders, metricsMetrics metrics.Metrics, logger log.Logger) (*worker.Worker, error) {
	notificationRepo := data.NewNotificationRepo(database, logger, metricsMetrics)
	notificationUsecase := biz.NewNotificationUsecase(notificationRepo, sendersSenders, metricsMetrics, logger)
	workerWorker := newWorker(notificationUsecase, logger)
	return workerWorker, nil
}
