// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2/log"
	"notifications/internal/biz"
	"notifications/internal/conf"
	"notifications/internal/data"
	"notifications/internal/pkg/metrics"
	"notifications/internal/senders"
	"notifications/internal/worker"
)

// Injectors from wire.go:

// wireData init database
func wireData(confData *conf.Data, logger log.Logger) (*data.Data, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	return dataData, func() {
		cleanup()
	}, nil
}

func wireWorker(dataData *data.Data, sendersSenders *senders.Senders, metricsMetrics metrics.Metrics, logger log.Logger) (*worker.Worker, error) {
	notificationRepo := data.NewNotificationRepo(dataData, logger, metricsMetrics)
	notificationUsecase := biz.NewNotificationUsecase(notificationRepo, sendersSenders, metricsMetrics, logger)
	workerWorker := newWorker(notificationUsecase, logger)
	return workerWorker, nil
}
