log:
  level: ${LOG_LEVEL:debug} # vendor/github.com/go-kratos/kratos/v2/log/level.go
metrics:
  address: ${METRICS_ADDRESS:localhost:8125}
  mute: ${METRICS_MUTE:true}
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: host=${POSTGRES_HOST:localhost} port=${POSTGRES_PORT:5432} user=${POSTGRES_USER:postgres} password=${POSTGRES_PASS:postgres} dbname=${POSTGRES_DB:notifications} sslmode=disable
    migrate: ${DATA_DATABASE_MIGRATE:soft} # (soft|hard|none)
    debug: ${DATA_DATABASE_DEBUG:false}
senders:
  plain:
    file: ${SENDERS_PLAIN_FILE:./messages.log}
  email:
    from: ${SENDERS_EMAIL_FROM}
    address: ${SENDERS_EMAIL_ADDRESS}
    username: ${SENDERS_EMAIL_USERNAME}
    password: ${SENDERS_EMAIL_PASSWORD}
