server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: postgres
    source: ${POSTGRES_USER:postgres}:${POSTGRES_PASS:postgres}@tcp(${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432})/${POSTGRES_DB:postgres}
