log:
  level: ${LOG_LEVEL:debug} # vendor/github.com/go-kratos/kratos/v2/log/level.go
metrics:
  address: ${METRICS_ADDRESS:localhost:8125}
  mute: ${METRICS_MUTE:true}
server:
  http:
    addr: ${SERVER_HTTP_ADDR:0.0.0.0:8000}
    timeout: ${SERVER_HTTP_TIMEOUT:1s}
  grpc:
    addr: ${SERVER_GRPC_ADDR:0.0.0.0:9000}
    timeout: ${SERVER_GRPC_TIMEOUT:1s}
data:
  database:
    driver: postgres
    source: host=${POSTGRES_HOST:localhost} port=${POSTGRES_PORT:5432} user=${POSTGRES_USER:postgres} password=${POSTGRES_PASS:postgres} dbname=${POSTGRES_DB:notifications} sslmode=disable
    migrate: ${DATA_DATABASE_MIGRATE:soft} # (soft|hard|none)
    debug: ${DATA_DATABASE_DEBUG:false}
auth:
  jwt:
    secret: ${AUTH_JWT_SECRET}
senders:
  plain:
    file: ${SENDERS_PLAIN_FILE:./messages.log}
  email:
    from: ${SENDERS_EMAIL_FROM}
    address: ${SENDERS_EMAIL_ADDRESS}
    username: ${SENDERS_EMAIL_USERNAME}
    password: ${SENDERS_EMAIL_PASSWORD}
  telegram:
    botToken: ${SENDERS_TELEGRAM_BOT_TOKEN}
  sms:
    aero:
      email: ${SENDERS_SMS_AERO_EMAIL}
      apiKey: ${SENDERS_SMS_AERO_API_KEY}
